Variablen:

  ClientSide:
    Prefix: "!"
    Token: "ODI4MjI5MTYxNjEyMjE0Mjky.YGmigw.Vg2fUHtnq9o0rqJiL5imzWtzLqw"
    MongoDB: "mongodb+srv://Drageast:Schmidt04@cluster0.r1bgi.mongodb.net/Die_Botin?retryWrites=true&w=majority"
    Webhook: "https://discordapp.com/api/webhooks/828241260425773086/O5HK2TedgGkxQmrVnP50cfaQ6YQIZidunuU9RWqggexXlV_aRe-Kj7ftShfN_P4RgMNB"
    Status: 2

  Dev_IDs:
    Drageast: 431017472083099660

  UniversalEmoji:
    Vorhut: <:Vorhut:828541360063381536>
    Schmelztiegel: <:Schmelztiegel:828541272246714400>
    Gambit: <:Gambit:828541228470894603>
    Raid: <:Raids:828541314450718741>

  SpecifiedChannels:
    Welcome: "allgemein"

Bilder:

  Vorhut: "https://i.imgur.com/nz0kSOV.jpg"
  Schmelztiegel: "https://i.imgur.com/mU2kjaN.jpg"
  Gambit: "https://i.imgur.com/DhDebKD.jpg"
  Raid: "https://i.imgur.com/rDVZY5m.jpg"

Embed:

  HTitle: "Ein Fehler ist aufgetreten."
