Variablen:

  ClientSide:

    Prefix: ""
    Token: ""

    MongoDB:

      Connection: ""
      Base: ""
      Uccount: ""
      Config: ""

    Status:

      ID: 1
      Text: ""

    ClientWebhooks:

      ErrorHook: ""
      TwitterHook: ""

  TwitterSide:

    API_Key: ""
    API_SECRET_Key: ""
    BEARER_Token: ""
    ACCESS_Token: ""
    ACCESS_SECRET_Token: ""

  Universals:

    Emojis:
      CustomGuild:
        Vorhut: <:Vorhut:>
        Schmelztiegel: <:Schmelztiegel:>
        Gambit: <:Gambit:>
        Raid: <:Raids:>

      Standart:
        Accept: ""

    Roles:

      Standart: ""

      ServerTeam:

        Owner: ""
        Developer: ""
        Administrator: ""

    Channels:

      Welcome: ""
      SpielerSuche: [ "", "", "", "", "" ]
      SupportChannelVOICE: 
      AdminChat: 

Bilder:

  Vorhut: ""
  Schmelztiegel: ""
  Gambit: ""
  Raid: ""

Embed:

  HTitle: "Ein Fehler ist aufgetreten."
