Variablen:

  ClientSide:
    Prefix: "!"
    Token: "ODI4MjI5MTYxNjEyMjE0Mjky.YGmigw.Vg2fUHtnq9o0rqJiL5imzWtzLqw"
    MongoDB: "mongodb+srv://Drageast:Schmidt04@cluster0.r1bgi.mongodb.net/Die_Botin?retryWrites=true&w=majority"
    Webhook: "https://discordapp.com/api/webhooks/829406759524368444/SZhAiFwZvPqHk4hDBaJlkAhClHYy2Yf_v1xSTjfC7ApuZMNiE-3eORQMUsQigTsZmclI"
    Status: 1

  Dev_IDs:
    Drageast: 431017472083099660

  UniversalEmoji:
    Vorhut: <:Vorhut:829406277716279346>
    Schmelztiegel: <:Schmelztiegel:829406183701086238>
    Gambit: <:Gambit:829406147252977675>
    Raid: <:Raids:829406226722324520>

  SpecifiedRoles:
    Standart: "Mitglied"

  SpecifiedChannels:
    Welcome: "willkommen"

Bilder:

  Vorhut: "https://i.imgur.com/nz0kSOV.jpg"
  Schmelztiegel: "https://i.imgur.com/mU2kjaN.jpg"
  Gambit: "https://i.imgur.com/DhDebKD.jpg"
  Raid: "https://i.imgur.com/rDVZY5m.jpg"

Embed:

  HTitle: "Ein Fehler ist aufgetreten."
